compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { binding = "CACHE", id = "9b90bf3df7a6448ba65be8805d5d1a01" }
]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "wealth"
database_id = "398984a7-aeca-4591-9ac1-5987833efe11"
