compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "CACHE"
id = "cache"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "wealth"
database_id = "wealth"
